### PR TITLE
First Commit

### PR DESCRIPTION
**Pull request by parulc7**

### CODE REVIEW

**Comment by hackrush01** [comment]
Needs a lot of changes,
1st Name is GameInfo not Game-Info
2nd CPP-2048 mein typo h
3rd Java ka link click karne par last mein logo ki image broken h

**Comment by parulc7** [comment]
Figured it out later. I will do the changes.

**Comment by modivivek** [comment]
Already a PI is merged so start working on that asap.

regards
hackrush

**Comment by modihere** [comment]
Already a PI is merged so start working on that asap.

regards
hackrush

**Pull request closed without merging**
